business_divsion        = "leenaai"
environment             = "dev"
resource_group_name     = "rg"
resource_group_location = "centralindia"
kubernetes_version      = "1.26.6"
system_node_count       = 1
system_min_node_count   = 1
system_max_node_count   = 2
user_node_pool_name     = "userpool"
user_node_count         = 1
# user_min_node_count = 1
# user_max_node_count = 2